In [ ]:
#ESERCITAZIONE W10D1 - Verrecchia Isabella


In [5]:
#ESERCIZIO 1: Abbiamo una lista di liste: Che tipo di struttura dati o matematica potrebbe rappresentare? 
#Notare che tutte le liste "interne" sono della stessa dimensione Come facciamo per accedere ad un elemento in particolare?

mat = [[0, 1, 2, 3, 4], #Ha la struttura di una matrice
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]]
#per accedere al singolo elemento, bisogna indicare l'indice di riga e di colonna
print(mat[2][3])
print (mat[0][4])



13
4


In [16]:
#ESERCIZIO 2: Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() 
#e la variabile .pi la riconoscete?
import math

help(math.sin) #la funzione seno e coseno ha come argomento l'angolo espresso in radianti
print(math.sin(30))
print(math.cos(15))
print(math.factorial(5))

#la variabile .pi è il pi-greco (3.14)

Help on built-in function sin in module math:

sin(x, /)
    Return the sine of x (measured in radians).

-0.9880316240928618
-0.7596879128588213
120


In [18]:
#ESERCIZIO 3: Proviamo a eseguire math.degrees(math.pi) Qual è e cosa significa il risultato? 
#Per saperne di più su questa funzione possiamo usare help(math.degrees)

math.degrees(math.pi)
help(math.degrees)  #math.degrees converte l'angolo da radianti a gradi

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [24]:
#ESERCIZIO 4: L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno:trasformiamola in un array NumPy (casting): 
#lst = np.array(lst) e rispondiamo alle domande del CEO della Object SpA:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

!pip install numpy
import numpy as np

lst = np.array(lst)


In [39]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst = np.array(lst)

#qual è stata la vendita massima mensile? E quella minima?
massimo = numpy.max(lst)
print("La vendita massima mensile è:", massimo)
minimo = numpy.min(lst)
print("La vendita minima mensile è:", minimo)
#quali sono le vendite mensili maggiori di 5000 oggetti? E quante ne sono?
vendite_maggiori = lst > 5000
print(lst[vendite_maggiori])
print("Le vendite maggiori di 5000 sono:", lst[vendite_maggiori].size)

#quali sono le vendite minori di 3000 oggetti?
vendite_minori = lst < 3000
print(lst[vendite_minori])

#in media quanti oggetti sono stati venduti al mese?
media_vendite = np.mean(lst)
print("Il valore medio delle vendite è:", media_vendite)

La vendita massima mensile è: 8150
La vendita minima mensile è: 1280
[5500 7200 6410 8150 7100 5350]
Le vendite maggiori di 5000 sono: 6
[2000 1280 1900 2500]
Il valore medio delle vendite è: 4634.166666666667


In [40]:
#ESERCIZIO 5: Consideriamo il seguente dizionario:

fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
#Consideriamo ora la seguente Series:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))
#Possiamo accedere alle stesse informazioni nello stesso modo: 
fatturati_dict[1997] 
fatturati_series[1997]

#Dunque qual è la differenza tra i due tipi di dato? Cosa potremmo fare con la Series che non possiamo fare con il dizionario?
#Un dizionario è una struttura dati nativa di Python, che contiene coppie chiave-valore, mentre una Series fa parte della libreria Pandas ed è 
#una colonna di dati etichettata. la differenza sostanziale è che con la Series si ha una visualizzazione tabellare e soprattutto si possono fare
# operazioni matematiche (analizzare, filtrare e manipolare dati numerici)


12000

In [43]:
#ESERCIZIO 6: L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray:
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000] )

#L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi:  con un ciclo for e con il masking

#1 modo: for
for stipendio in stipendi:
    stipendio_raddoppiato= stipendio*2
    print(stipendio_raddoppiato)

#2 modo: masking

stipendio_doppio= stipendi *2
print(stipendio_doppio)

200
400
600
800
1000
1200
1400
1600
1800
2000
[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [61]:
#ESERCIZIO 7: Scrivere un programma che, data una lista di numeri, fornisca in output i tre numeri più grandi; gestire il caso in cui la lista 
#sia più corta di tre, e quando uno o più dei numeri selezionati sono uguali.

lista = [15, 30, 2, 63, 6, 42, 75, 24, 48, 63, 19, 51, 8] #creo una lista con valori casuali
#lista = sorted(lista, reverse = True) #li riordino --> MEGLIO METTERLO NELL'IF
#print(lista)
#lista[:3]
lista = list(set(lista)) #lo metto prima del ciclo così in automatico gestisce subito i duplicati!!!!

if len(lista) >3:
    lista = sorted(lista, reverse = True)
    print(lista[:3])
else:
    print(lista)
#per gestire i dati mancanti uso il set!
lista = set(lista)
lista =list (lista)
lista

[75, 63, 51]


[2, 6, 8, 42, 75, 15, 48, 51, 19, 24, 30, 63]

In [71]:
#ESERCIZIO 8: Scrivere un programma che 
#• in input acquisisce una lista di numeri e un numero K 
#• in output, dovrà restituire la media di tutti i numeri nella lista maggiori o uguali a K 
#• se non ce ne dovesse essere nessuno, dovrà stampare a schermo un messaggio adeguato.

dati = [2, 6, 8, 42, 75, 15, 48, 51, 19, 24, 30, 63]
dati = np.array(dati) # lo trasformo in array così posso fare il calcolo della media in modo più facile
K = 20

filtro = dati >= K   #NB: AVREI FATTO CON FOR, MA USANDO ARRAY E' PIU' FACILE!!!
media = dati[filtro].mean()
print("La media di tutti i numeri > K è:", round(media,2))

#manca il caso in cui non c'è nessuno --> provo con if



La media di tutti i numeri > K è: 47.57


In [72]:
#ESERCIZIO 9: Scrivere un programma che, data una lista di numeri, come output stamperà lo stesso numero di asterischi su righe diverse, 
#ottenendo una semplice visualizzazione grafica

numeri = [4, 8, 3, 2, 10]

for numero in numeri:
    print("*" * numero)

****
********
***
**
**********


In [78]:
#ESERCIZIO 10: Abbiamo una lista di codici fiscali:
lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", 
            "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]
#trovare i codici fiscali che contengono "95", metterli in una lista, e alla fine stamparla;
nuova_lista = []

for codice in lista_cf:
    if "95" in codice:
        nuova_lista.append(codice)
    
print(nuova_lista)
#inoltre, per ognuno di essi, stampare a video i caratteri relativi al nome e quelli relativi al cognome.        

for codice in nuova_lista:   #estraggo dalla nuova lista creata solo le lettere di nome e cognome
    print("Nome:", codice[:3],"Cognome:", codice[3:6]) 

['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']
Nome: ABC Cognome: DEF
Nome: STU Cognome: VWX
Nome: DEF Cognome: GHI


In [84]:
#ESERCIZIO 11: Abbiamo tre liste della stessa lunghezza, dove ogni elemento nella medesima posizione si riferisce ai dati dello stesso studente: 
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"] 
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"] 
edizioni = [1, 2, 3, 2, 2, 1, 3, 3] 

# Stampare a video tutti e soli gli studenti che frequentano una prima edizione; non tutti i dati potrebbero essere necessari.

range(len(studenti)) #mi permette di scorrere negli elementi delle liste(considerato che hanno tutte la stessa lunghezza)

for indice in range(len(studenti)):
    studente = studenti[indice]  #in questo modo io associo studente e edizione all'indice che cambia con il ciclo
    edizione = edizioni[indice]
    if edizione ==1:
        print(studente)

Alex
Faith


In [85]:
#ESERCIZIO 10:Abbiamo una lista di stringhe di prezzi in dollari, che erroneamente sono stati scritti con il simbolo dell'euro: 
prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"] 
#cambiare il simbolo dell'euro (€) in quello del dollaro ($) per ogni stringa nella lista; il risultato sarà memorizzato in un'altra lista.
nuovi_prezzi = []

for prezzo in prezzi:
    nuovo_prezzo = prezzo.replace("€","$")
    nuovi_prezzi.append(nuovo_prezzo)

print(nuovi_prezzi)
    

['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


In [90]:
#ESERCIZIO 11: Abbiamo una lista di studenti: 
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"] 
#vogliamo dividere gli studenti in due squadre per un campionato di Uno nel seguente modo: selezioneremo i nomi in posizione pari per un squadra, 
#e i nomi in posizione dispari per l'altra. Creiamo due liste per ogni squadra, e alla fine visualizziamole.

squadra_pari = studenti[::2]
squadra_dispari = studenti[1::2]

print("squadra pari:", squadra_pari)
print("squadra dispari:", squadra_dispari)



squadra pari: ['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']
squadra dispari: ['Bob', 'Dan', 'Faith', 'Henry', 'John']


In [91]:
studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"] 
squadra_pari = []
squadra_dispari = []
#provo con ciclo for

for indice in range(len(studenti)):
    studente = studenti[indice]
    if indice % 2 ==0:
        squadra_pari.append(studente)
    else:
        squadra_dispari.append(studente)
        
print("squadra pari:", squadra_pari)
print("squadra dispari:", squadra_dispari)


squadra pari: ['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']
squadra dispari: ['Bob', 'Dan', 'Faith', 'Henry', 'John']


In [97]:
#ESERCIZIO 12: Esercizio Abbiamo una lista con i guadagni degli ultimi 12 mesi (supponiamo da Gennaio a Dicembre): 
guadagni = [100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50] 
#dobbiamo confrontare, stampando tutto a video, il guadagno di ogni mese con la media dei guadagni precedenti, e specificare nell'output 
#se il guadagno attuale è maggiore o minore della media dei precedenti.

precedenti = [] #guadagni mesi precedenti (rispetto al mese corrente)
contatore = 1   #parto dal secondo mese, perchè dal primo non ho nessun confronto precedente da fare

for guadagno in guadagni:
    if len(precedenti)==0:
        print("Mese", contatore, ":", guadagno, "€")
    else:
        media_mesi_precedenti = round(np.mean(precedenti),2)
        print("Mese", contatore, ":", guadagno, "€ - La media dei mesi precedenti è:", media_mesi_precedenti)
        if guadagno < media_mesi_precedenti:
            print("Il guadagno è minore!")
        else:
            print("Il guadagno è maggiore!")
    precedenti.append(guadagno)
    contatore +=1
   

Mese 1 : 100 €
Mese 2 : 90 € - La media dei mesi precedenti è: 100.0
Il guadagno è minore!
Mese 3 : 70 € - La media dei mesi precedenti è: 95.0
Il guadagno è minore!
Mese 4 : 40 € - La media dei mesi precedenti è: 86.67
Il guadagno è minore!
Mese 5 : 50 € - La media dei mesi precedenti è: 75.0
Il guadagno è minore!
Mese 6 : 80 € - La media dei mesi precedenti è: 70.0
Il guadagno è maggiore!
Mese 7 : 90 € - La media dei mesi precedenti è: 71.67
Il guadagno è maggiore!
Mese 8 : 120 € - La media dei mesi precedenti è: 74.29
Il guadagno è maggiore!
Mese 9 : 80 € - La media dei mesi precedenti è: 80.0
Il guadagno è maggiore!
Mese 10 : 20 € - La media dei mesi precedenti è: 80.0
Il guadagno è minore!
Mese 11 : 50 € - La media dei mesi precedenti è: 74.0
Il guadagno è minore!
Mese 12 : 50 € - La media dei mesi precedenti è: 71.82
Il guadagno è minore!
